### ISSUE TITLE
Works only when importing CSS from JS

### ISSUE THREAD

**Issue by jsierles** [martonlederer/esbuild-plugin-postcss2#2]
This plugin is working if I import css from a JS file. However, I'd like to use a CSS file as an entrypoint to [allow watch mode](https://esbuild.github.io/api/#watch) to work when making CSS changes. Is this possible using the esbuild plugin system?

**Comment by martonlederer** [comment]
I'm not sure if that is possible. You can check out the esbuild docs [here](https://esbuild.github.io/) tho.

**Comment by martonlederer** [comment]
Okay, so it is possible to use css entries:
https://esbuild.github.io/content-types/#css

Have you tried it?

**Comment by jsierles** [comment]
Yes, I tried but the postcss plugin is not invoked. I didn't look yet, but I'd guess that plugins may not apply yet to CSS.

**Comment by g45t345rt** [comment]
You should implement watch files on your own with 
https://www.npmjs.com/package/chokidar

For example: https://github.com/g45t345rt/esbuild-firebase-ssr-react-ts/blob/master/bundle.js#L82

**Comment by jsierles** [comment]
I think I confused two issues here. The main issue is that, even without watch mode, this plugin does not seem to apply to CSS entry points. Here's an example error that happens when importing tailwind in a CSS file used as an entry point:

**Comment by g45t345rt** [comment]
Yep we are mixing two issues here.

The first one is that esbuild does not watch files other than js,jsx,ts,tsx so that's why you have to make your own watcher.

And for your issue, the plugin wont work if you use CSS file as an entry point.
It's because the plugin is only parsing CSS files that are being resolved from esbuild and not actually compiled.

So this https://github.com/martonlederer/esbuild-plugin-postcss2/blob/577e566f36dd0fe389aa6a9a9e34297023e2bfe3/src/index.ts#L58 never gets hit.

We will have to use https://github.com/martonlederer/esbuild-plugin-postcss2/blob/577e566f36dd0fe389aa6a9a9e34297023e2bfe3/src/index.ts#L58 if we want it to work.

**Comment by jsierles** [comment]
OK - would it be interesting to do that? 

After some testing, tt looks like esbuild _does_ watch css files that are used as entrypoints, but _not_ the files they import. Also, the postcss2 plugin _does_ get invoked for files imported from an entrypoint, but not for the entrypoint itself. So by moving everything to an imported file, everything works except for the watcher.

Given this, I agree the right move would be to use a custom watcher until `esbuild` is able to watch CSS imports.

**Comment by g45t345rt** [comment]
Okay, I was able to make it work with a small fix inside of `onResolve` instead of using `onLoad` like I initially thought.

My fork as the changes
https://github.com/g45t345rt/esbuild-plugin-postcss2

I will wait for @martonlederer to review my current pull request https://github.com/martonlederer/esbuild-plugin-postcss2/pull/5
before pushing this one.

**Comment by g45t345rt** [comment]
@Zertz neat thanks for letting us know

**Comment by g45t345rt** [comment]
@Zertz Thanks agaun for the info
I was able to use `watchFiles: []` inside onResolve https://esbuild.github.io/plugins/#resolve-results and it worked like magic. 

I've created a new pull request with the changes that I've made here
https://github.com/martonlederer/esbuild-plugin-postcss2/pull/6

If you guys want to try it now before @martonlederer accept the pull and makes the npm publish, you can always install directly from my github branch using
`npm install https://github.com/g45t345rt/esbuild-plugin-postcss2`

**Comment by martonlederer** [comment]
Closed #6
